*** Variables ***
${menu}
${menu_422}
${name}
${keyword}
${reply_type}
${content}
${name_422}
${keyword_422}
${reply_type_422}
${content_422}
${category}
${category_422}
${page_num}
${page_size}
${page_num_422}
${page_size_422}
${start_time}
${end_time}
${people_day_num}
${expect_time}
${expect_day}
${expect_type}
${expect_hour}
${service_groups}
${day_in_week}
${spec_people_day_num}
${time_loop_set}
${start_time_422}
${end_time_422}
${people_day_num_422}
${expect_time_422}
${expect_day_422}
${expect_type_422}
${expect_hour_422}
${service_groups_422}
${day_in_week_422}
${spec_people_day_num_422}
${time_loop_set_422}
${group_time_range}
${people_num}
${status}
${car_washers}
${group_time_range_422}
${people_num_422}
${status_422}
${car_washers_422}
${card_name}
${days}
${grant_way}
${price}
${first_price}
${recharge_price}
${first_recharge_price}
${coupons}
${card_remark}
${card_name_422}
${days_422}
${grant_way_422}
${price_422}
${first_price_422}
${recharge_price_422}
${first_recharge_price_422}
${coupons_422}
${card_remark_422}
${card_id}
${card_id_422}
${order_by}
${order_by_422}
${user_id}
${mobile}
${mode}
${created_section}
${user_id_422}
${mobile_422}
${mode_422}
${created_section_422}
${section}
${section_422}
${promoter_no}
${promoter_no_422}
${choose_car_model_id}
${cost_price}
${min_cost_price}
${max_cost_price}
${min_price}
${max_price}
${wash_normal_price}
${min_wash_normal_price}
${max_wash_normal_price}
${wash_group_price}
${min_wash_group_price}
${max_wash_group_price}
${member_price}
${min_member_price}
${max_member_price}
${commission_percent}
${standard_time}
${special_car_models}
${description}
${choose_car_model_id_422}
${cost_price_422}
${min_cost_price_422}
${max_cost_price_422}
${min_price_422}
${max_price_422}
${wash_normal_price_422}
${min_wash_normal_price_422}
${max_wash_normal_price_422}
${wash_group_price_422}
${min_wash_group_price_422}
${max_wash_group_price_422}
${member_price_422}
${min_member_price_422}
${max_member_price_422}
${commission_percent_422}
${standard_time_422}
${special_car_models_422}
${description_422}
${car_brand}
${car_series_name}
${car_scale}
${car_model}
${car_brand_422}
${car_series_name_422}
${car_scale_422}
${car_model_422}
${car_model_id}
${car_model_id_422}
${intelligent_service_id}
${car_brand_name}
${intelligent_service_id_422}
${car_brand_name_422}
${car_series}
${car_series_422}
${coupon_pool_id}
${created_number}
${coupon_pool_id_422}
${created_number_422}
${coupon_code_name}
${coupon_code_remark}
${coupon_code_name_422}
${coupon_code_remark_422}
${coupon_code_record_id}
${coupon_code_no}
${car_id}
${coupon_code_record_id_422}
${coupon_code_no_422}
${car_id_422}
${promoter_remark}
${promoter_remark_422}
${promoter_id}
${promoter_id_422}
${order_no}
${car_washer}
${parking_id}
${order_no_422}
${car_washer_422}
${parking_id_422}
${username}
${birthday}
${ID_card}
${address}
${sex}
${password}
${username_422}
${birthday_422}
${ID_card_422}
${address_422}
${sex_422}
${password_422}
${wash_area_id}
${car_washer_ids}
${wash_area_id_422}
${car_washer_ids_422}
${robot_num}
${robot_num_422}
${wash_group_no}
${valid_start_section}
${wash_group_no_422}
${valid_start_section_422}
${refunds}
${refund_description}
${refunds_422}
${refund_description_422}
${close_description}
${close_description_422}
${submit_section}
${wash_seconds}
${order_type}
${submit_section_422}
${wash_seconds_422}
${order_type_422}
${admin_remark}
${admin_remark_422}
${province}
${city}
${district}
${service_type}
${province_422}
${city_422}
${district_422}
${service_type_422}
${coupon_template_name}
${discount_money}
${coupon_number}
${allow_gain_number}
${coupon_type}
${discount}
${condition_money}
${allow_use_days}
${is_point}
${service_types}
${order_types}
${service_group_ids}
${wash_area_ids}
${parking_ids}
${coupon_template_name_422}
${discount_money_422}
${coupon_number_422}
${allow_gain_number_422}
${coupon_type_422}
${discount_422}
${condition_money_422}
${allow_use_days_422}
${is_point_422}
${service_types_422}
${order_types_422}
${service_group_ids_422}
${wash_area_ids_422}
${parking_ids_422}
${coupon_id}
${coupon_id_422}
${record_num_last_30_day}
${average_price_last_30_day}
${wash_interval}
${user_type}
${record_num_last_30_day_422}
${average_price_last_30_day_422}
${wash_interval_422}
${user_type_422}
${user_ids}
${user_ids_422}
${coupon_name}
${coupon_name_422}
${point_remark}
${point_remark_422}
${coupon_point_record_id}
${is_used}
${coupon_point_record_id_422}
${is_used_422}
${service_name}
${commission_price}
${service_name_422}
${commission_price_422}
${service_group_name}
${service_original_price}
${pricing_strategy}
${membership_price}
${wash_normal_percent}
${wash_group_percent}
${membership_percent}
${service_ids}
${intelligent_service_ids}
${service_group_name_422}
${service_original_price_422}
${pricing_strategy_422}
${membership_price_422}
${wash_normal_percent_422}
${wash_group_percent_422}
${membership_percent_422}
${service_ids_422}
${intelligent_service_ids_422}
${subscribe_name}
${subscribe_day_num}
${subscribe_expect_time}
${subscribe_expect_day}
${subscribe_name_422}
${subscribe_day_num_422}
${subscribe_expect_time_422}
${subscribe_expect_day_422}
${userid}
${invited_userid}
${first_car_id}
${first_mobile}
${userid_422}
${invited_userid_422}
${first_car_id_422}
${first_mobile_422}
${wash_user_group_id}
${wash_user_group_id_422}
${wash_user_group_ids}
${wash_user_group_ids_422}
${turntable_id}
${prize_name}
${turntable_id_422}
${prize_name_422}
${car_type}
${car_type_422}
${car_color}
${car_frame_no}
${licensed_time}
${car_year}
${car_images}
${car_tire_pressure}
${car_color_422}
${car_frame_no_422}
${licensed_time_422}
${car_year_422}
${car_images_422}
${car_tire_pressure_422}
${entry_time}
${lon}
${lat}
${phase}
${floor}
${zone}
${space_no}
${ownership}
${entry_time_422}
${lon_422}
${lat_422}
${phase_422}
${floor_422}
${zone_422}
${space_no_422}
${ownership_422}
${opinion}
${is_refund}
${opinion_422}
${is_refund_422}
${customer_service_no}
${reason}
${order_status}
${start_section}
${customer_service_no_422}
${reason_422}
${order_status_422}
${start_section_422}
${last_section}
${last_section_422}
${qrcode_remark}
${qrcode_remark_422}
${car_move_qrcode_id}
${car_move_qrcode_id_422}
${level}
${level_422}
${parking_name}
${alias_name}
${out_parking_id}
${parking_banners}
${service_introduce}
${position}
${parking_name_422}
${alias_name_422}
${out_parking_id_422}
${parking_banners_422}
${service_introduce_422}
${position_422}
${notice_mail}
${notice_mail_422}
${banners}
${banners_422}
${order_id}
${order_id_422}
${type}
${type_422}
${parking_coupon_no}
${parking_coupon_no_422}
${before_wash_images}
${after_wash_images}
${wash_tags}
${dirty_percent}
${washer_remark}
${mark}
${before_wash_images_422}
${after_wash_images_422}
${wash_tags_422}
${dirty_percent_422}
${washer_remark_422}
${mark_422}
${page_limit}
${page_limit_422}
${car_ids}
${car_ids_422}
${radius}
${center}
${limit}
${radius_422}
${center_422}
${limit_422}
${wash_group_id}
${wash_group_id_422}
${condition}
${condition_422}
${grant_type}
${grant_type_422}
${refresh}
${refresh_422}
${pay_type}
${openid}
${pay_type_422}
${openid_422}
${popular_brand}
${popular_brand_422}
${brand_id}
${brand_id_422}
${car_series_id}
${car_series_id_422}
${nickName}
${avatarUrl}
${code}
${rawData}
${signature}
${encryptedData}
${iv}
${nickName_422}
${avatarUrl_422}
${code_422}
${rawData_422}
${signature_422}
${encryptedData_422}
${iv_422}
${client_id}
${secret}
${unionid}
${client_id_422}
${secret_422}
${unionid_422}
${serie}
${captcha}
${union_id}
${mn_open_id}
${serie_422}
${captcha_422}
${union_id_422}
${mn_open_id_422}
${tokenid}
${tokenid_422}
${wash_able_group_id}
${wash_able_group_id_422}
${service_group_id}
${old_order_id}
${service_group_id_422}
${old_order_id_422}
${wash_normal_id}
${wxmp_remark}
${user_car_id}
${user_contact_id}
${car_place}
${wash_normal_id_422}
${wxmp_remark_422}
${user_car_id_422}
${user_contact_id_422}
${car_place_422}
${comment_status}
${comment_status_422}
${coupon_pool_ids}
${coupon_pool_ids_422}
${order_price}
${order_price_422}
${invite_code}
${invite_code_422}
${key}
${key_422}
${wash_record_id}
${wash_record_id_422}
${comment_remark}
${comment_remark_422}
${media_id}
${media_id_422}
${formid}
${formid_422}
${wx_nickname}
${wx_avatarurl}
${wx_nickname_422}
${wx_avatarurl_422}
