*** Variables ***
${menu}
${name}
${keyword}
${reply_type}
${content}
${category}
${page_num}
${page_size}
${start_time}
${end_time}
${people_day_num}
${expect_time}
${expect_day}
${expect_type}
${expect_hour}
${service_groups}
${day_in_week}
${spec_people_day_num}
${time_loop_set}
${group_time_range}
${people_num}
${status}
${car_washers}
${card_name}
${days}
${grant_way}
${price}
${first_price}
${recharge_price}
${first_recharge_price}
${coupons}
${card_remark}
${card_id}
${order_by}
${user_id}
${mobile}
${mode}
${created_section}
${section}
${promoter_no}
${choose_car_model_id}
${cost_price}
${min_cost_price}
${max_cost_price}
${min_price}
${max_price}
${wash_normal_price}
${min_wash_normal_price}
${max_wash_normal_price}
${wash_group_price}
${min_wash_group_price}
${max_wash_group_price}
${member_price}
${min_member_price}
${max_member_price}
${commission_percent}
${standard_time}
${special_car_models}
${description}
${car_brand}
${car_series_name}
${car_scale}
${car_model}
${car_model_id}
${intelligent_service_id}
${car_brand_name}
${car_series}
${coupon_pool_id}
${created_number}
${coupon_code_name}
${coupon_code_remark}
${coupon_code_record_id}
${coupon_code_no}
${car_id}
${promoter_remark}
${promoter_id}
${order_no}
${car_washer}
${parking_id}
${username}
${birthday}
${ID_card}
${address}
${sex}
${password}
${wash_area_id}
${car_washer_ids}
${robot_num}
${wash_group_no}
${valid_start_section}
${refunds}
${refund_description}
${close_description}
${submit_section}
${wash_seconds}
${order_type}
${admin_remark}
${province}
${city}
${district}
${service_type}
${coupon_template_name}
${discount_money}
${coupon_number}
${allow_gain_number}
${coupon_type}
${discount}
${condition_money}
${allow_use_days}
${is_point}
${service_types}
${order_types}
${service_group_ids}
${wash_area_ids}
${parking_ids}
${coupon_id}
${record_num_last_30_day}
${average_last_30_day}
${how_long_no_record}
${user_type}
${user_ids}
${coupon_name}
${is_used}
${coupon_point_record_id}
${point_remark}
${service_name}
${commission_price}
${service_time}
${service_group_name}
${service_original_price}
${pricing_strategy}
${membership_price}
${wash_normal_percent}
${wash_group_percent}
${membership_percent}
${service_ids}
${intelligent_service_ids}
${subscribe_name}
${subscribe_day_num}
${subscribe_expect_time}
${subscribe_expect_day}
${userid}
${invited_userid}
${first_car_id}
${first_mobile}
${wash_user_group_id}
${wash_user_group_ids}
${turntable_id}
${prize_name}
${car_type}
${car_color}
${car_frame_no}
${licensed_time}
${car_year}
${car_images}
${car_tire_pressure}
${entry_time}
${lon}
${lat}
${phase}
${floor}
${zone}
${space_no}
${ownership}
${opinion}
${is_refund}
${customer_service_no}
${reason}
${order_status}
${start_section}
${last_section}
${qrcode_remark}
${car_move_qrcode_id}
${level}
${parking_name}
${alias_name}
${out_parking_id}
${parking_banners}
${service_introduce}
${position}
${notice_mail}
${banners}
${order_id}
${mouth}
${parking_coupon_no}
${before_wash_images}
${after_wash_images}
${wash_tags}
${dirty_percent}
${washer_remark}
${mark}
${page_limit}
${car_ids}
${radius}
${center}
${limit}
${wash_group_id}
${condition}
${grant_type}
${refresh}
${pay_type}
${openid}
${popular_brand}
${brand_id}
${car_series_id}
${nickName}
${avatarUrl}
${code}
${rawData}
${signature}
${encryptedData}
${iv}
${client_id}
${secret}
${unionid}
${serie}
${captcha}
${union_id}
${mn_open_id}
${tokenid}
${wash_able_group_id}
${service_group_id}
${old_order_id}
${wash_normal_id}
${wxmp_remark}
${user_car_id}
${user_contact_id}
${car_place}
${comment_status}
${coupon_pool_ids}
${order_price}
${invite_code}
${key}
${wash_record_id}
${comment_remark}
${media_id}
${formid}
${wx_nickname}
${wx_avatarurl}
